fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    apt: "git://github.com/puppetlabs/puppetlabs-apt"
    vcsrepo: "https://github.com/puppetlabs/puppetlabs-vcsrepo"
    suricata: "https://github.com/naturalis/puppet-suricata.git"
    scirius: "https://github.com/naturalis/puppet-scirius.git"
    logrotate: "https://github.com/yo61/puppet-logrotate.git"
    role_logging: "https://github.com/naturalis/puppet-role_logging.git"
    wget: "https://github.com/maestrodev/puppet-wget.git"
    sensu: "https://github.com/sensu/sensu-puppet.git"

  symlinks:
    role_ids: "#{source_dir}"
